### ISSUE TITLE
1.7.0 release fails when used as a github release in Concourse

### ISSUE THREAD

**Issue by bstick12** [cloudfoundry-incubator/backup-and-restore-sdk-release#11]
We are using the following Concourse resource

```
- name: backup-and-restore-sdk-release
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: backup-and-restore-sdk-release
    access_token: ((token))
```

When using the v1.7.0 tag the artefact downloaded fails to process as it is an invalid tarball. 

Upon inspecting the tarball. We see the contents is a follows:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>88870798/f6f2ff46-5aa4-11e8-90a0-2f9beb9bbc85</Key><RequestId>1BB4DD73A15A1E5F</RequestId><HostId>XEevxyEqRTYvsCmEuPdrGXa5Lay/pbvMGG/YEpycByCICwE50LVGZkcFBPqkEg/C4K5RrCm0Ifs=</HostId></Error>root@14b34d60-f1c8-4ab4-705e-def0c4472b47
```
